name: Docker Build Firmware

on:
  push:
    branches: 
      - "**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        source .venv/bin/activate
        uv pip install -e ./ectf26_design/
        docker build -t build-hsm ./firmware
        make global.secrets GROUPS='0x7098 0xced7'
        make test.hsm PIN=123458 PERMS='0x7098=RWC:0xced7=RWC'
