name: Docker Build Firmware

on:
  push:
    branches: 
      - "**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        source .venv/bin/activate
        uv pip install -e ./ectf26_design/
        uv run secrets ./global.secrets 1 0x1111
        docker build -t build-hsm ./firmware
        docker run --rm -v ./firmware:/hsm -v ./global.secrets:/secrets/global.secrets:ro -v ./build:/out -e HSM_PIN='123abc' -e PERMISSIONS='1234=R--:4321=RWC' build-hsm