name: eCTF Test Submit

on:
  push:
    branches:
      - "release"   # run on all branches (change if you want)
      #- "CICD-test"
  workflow_dispatch:

jobs:
  ectf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Verify ectf command
        run: |
          uvx ectf --help

      - name: Configure ectf
        run: |
          printf "%s\n%s\n%s\n" \
          "${{ secrets.ectf_token }}" \
          "git@github.com:niklasekebergh-hub/UFSIT_eCTF_2026.git" \
          "https://api.ectf.mitre.org" | uvx ectf config
          
      - name: Submit test
        id: submit
        run: |
          echo "$GITHUB_SHA"
          OUTPUT=$(uvx ectf api test submit "$GITHUB_SHA")
          echo "$OUTPUT"
          TEST_ID=$(echo "$OUTPUT" | grep -oE '[a-f0-9-]{36}')
          echo "test_id=$TEST_ID" >> $GITHUB_OUTPUT

      - name: Wait for test result
        run: |
          TEST_ID="${{ steps.submit.outputs.test_id }}"
          echo "Waiting on test $TEST_ID"

          while true; do
            STATUS=$(uvx ectf api test ls | awk -v id="$TEST_ID" '$1 == id {print $3}')

            if [ -z "$STATUS" ]; then
              echo "Test not found yet..."
            else
              echo "Status: $STATUS"
            fi

            if [ "$STATUS" = "Succeeded" ]; then
              echo "Test succeeded"
              exit 0
            fi

            if [ "$STATUS" = "Failed" ]; then
              echo "Test failed"
              exit 1
            fi

            sleep 30
          done